#rf004
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf004
  labels:
    app: rf004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rf004
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rf004
    spec:
      containers:
        - name: rf004
          image: us-central1-docker.pkg.dev/deliveryandlogistic/deliveryandlogistic-images/rf004:v1.0.0
          ports:
            - containerPort: 3006
          env:
            - name: "USERS_PATH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: USERS_PATH
            - name: "SCORES_PATH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: SCORES_PATH
            - name: "POSTS_PATH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: POSTS_PATH
            - name: "OFFERS_PATH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: OFFERS_PATH
            - name: "ROUTES_PATH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: ROUTES_PATH      
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always
      volumes:
        - name: appsecrets-volume
          secret:
            secretName: appsecrets
---            
#--- HEALTHCHECK RF004
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: rf004-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3006
    type: HTTP
    requestPath: /rf004/posts/ping
---
#--- SERVICE RF004
kind: Service
apiVersion: v1
metadata:
  name: servicio-rf004
  annotations:
    cloud.google.com/backend-config: '{"default": "rf004-config"}'  
spec:
  type: NodePort
  selector:
    app: rf004
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006
      nodePort: 31025
#--- RF004
---