#UTILIDADES
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utilidades
  labels:
    app: utilidades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utilidades
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: utilidades
    spec:
      containers:
        - name: utilidades
          image: us-central1-docker.pkg.dev/deliveryandlogistic/deliveryandlogistic-images/utilidades:v1.0.0
          ports:
            - containerPort: 3004
          env:
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_USER
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_PASSWORD
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_HOST
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_PORT
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: DB_NAME
            - name: "USERS_PATH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: USERS_PATH        
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always
      volumes:
        - name: appsecrets-volume
          secret:
            secretName: appsecrets
---            
#--- HEALTHCHECK UTILIDADES
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: utilidades-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3001
    type: HTTP
    requestPath: /utilidades/ping
---
#--- SERVICE UTILIDADES
kind: Service
apiVersion: v1
metadata:
  name: servicio-utilidades
  annotations:
    cloud.google.com/backend-config: '{"default": "utilidades-config"}'  
spec:
  type: NodePort
  selector:
    app: utilidades
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
      nodePort: 31023
#--- UTILIDADES
---